### ISSUE TITLE
Password hash input

### ISSUE THREAD

**Issue by ronnieflip** [HunnicCyber/SharpSniper#1]
**Note an issue per-say:**
Am wondering how i can make this be able to support a hash for the password input

**Comment by HunnicCyber** [comment]
https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.eventing.reader.sessionauthentication

I believe there might be a away.

I go it a go over the weekend and would appreciate any progress you make to
be shared.

Tom

**Comment by ronnieflip** [comment]
Interesting reference mate. I'll leave this open so that i can post my solution here.
Thanks

**Comment by bao7uo** [comment]
Enabled in #2 due to support for authenticating with the process user's token. Use mimikatz etc. to pth and then `SharpSniper.exe username` will do the trick :)
